1. tentukan library yang digunakan

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

2. load dataset

In [8]:
survey_lung_cancer_dataset = pd.read_csv('survey lung cancer.csv')

In [9]:
survey_lung_cancer_dataset.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [14]:
survey_lung_cancer_dataset['GENDER']=survey_lung_cancer_dataset['GENDER'].map({'M':1, 'F':0})
survey_lung_cancer_dataset

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,0,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,0,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,0,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,1,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,1,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,1,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,1,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [15]:
survey_lung_cancer_dataset['LUNG_CANCER']=survey_lung_cancer_dataset['LUNG_CANCER'].map({'YES':1, 'NO':0})
survey_lung_cancer_dataset

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,0,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,0,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,0,56,1,1,1,2,2,2,1,1,2,2,2,2,1,1
305,1,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1
306,1,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1
307,1,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1
308,1,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1

In [16]:
survey_lung_cancer_dataset.shape

(309, 16)

In [18]:
survey_lung_cancer_dataset['LUNG_CANCER'].value_counts()

1    270
0     39
Name: LUNG_CANCER, dtype: int64

In [19]:
# memisahkan data dan label
X = survey_lung_cancer_dataset.drop(columns='LUNG_CANCER', axis=1)
Y = survey_lung_cancer_dataset['LUNG_CANCER']

In [20]:
print (X)

     GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1
1         1   74        2               1        1              1
2         0   59        1               1        1              2
3         1   63        2               2        2              1
4         0   63        1               2        1              1
..      ...  ...      ...             ...      ...            ...
304       0   56        1               1        1              2
305       1   70        2               1        1              1
306       1   58        2               1        1              1
307       1   67        2               1        2              1
308       1   62        1               1        1              2

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2
1                  2         2         2         1                  1
2                  1         2         1         2                  1
3                  1         1         1         1                  2
4                  1         1         1         2                  1
..               ...       ...       ...       ...                ...
304                2         2         1         1                  2
305                1         2         2         2                  2
306                1         1         2         2                  2
307                1         2         2         1                  2
308                1         2         2         2                  2

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN
0           2                    2                      2           2
1           1                    2                      2           2
2           2                    2                      1           2
3           1                    1                      2           2
4           2                    2                      1           1
..        ...                  ...                    ...         ...
304         2                    2                      2           1
305         2                    2                      1           2
306         2                    1                      1           2
307         2                    2                      1           2
308         1                    1                      2           1

[309 rows x 15 columns]

In [21]:
print (Y)

0      1
1      1
2      0
3      0
4      0
      ..
304    1
305    1
306    1
307    1
308    1
Name: LUNG_CANCER, Length: 309, dtype: int64

3. standarisasi data

In [22]:
scaler=StandardScaler()

In [23]:
scaler.fit(X)

StandardScaler()

In [25]:
standarized_data=scaler.transform(X)

In [26]:
print(standarized_data)

[[ 0.95257934  0.77185028 -1.13529242 ...  0.74873631  1.06350105
   0.892475  ]
 [ 0.95257934  1.38182914  0.88083033 ...  0.74873631  1.06350105
   0.892475  ]
 [-1.04978132 -0.44810745 -1.13529242 ...  0.74873631 -0.94029056
   0.892475  ]
 ...
 [ 0.95257934 -0.57010322  0.88083033 ... -1.33558369 -0.94029056
   0.892475  ]
 [ 0.95257934  0.52785873  0.88083033 ...  0.74873631 -0.94029056
   0.892475  ]
 [ 0.95257934 -0.08212013 -1.13529242 ... -1.33558369  1.06350105
  -1.12047956]]

In [27]:
X=standarized_data
Y=survey_lung_cancer_dataset['LUNG_CANCER']

In [28]:
print (X)
print(Y)

[[ 0.95257934  0.77185028 -1.13529242 ...  0.74873631  1.06350105
   0.892475  ]
 [ 0.95257934  1.38182914  0.88083033 ...  0.74873631  1.06350105
   0.892475  ]
 [-1.04978132 -0.44810745 -1.13529242 ...  0.74873631 -0.94029056
   0.892475  ]
 ...
 [ 0.95257934 -0.57010322  0.88083033 ... -1.33558369 -0.94029056
   0.892475  ]
 [ 0.95257934  0.52785873  0.88083033 ...  0.74873631 -0.94029056
   0.892475  ]
 [ 0.95257934 -0.08212013 -1.13529242 ... -1.33558369  1.06350105
  -1.12047956]]
0      1
1      1
2      0
3      0
4      0
      ..
304    1
305    1
306    1
307    1
308    1
Name: LUNG_CANCER, Length: 309, dtype: int64

4. memisahkan data training dan data testing

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [33]:
print(X.shape, X_train.shape, X_test.shape)

(309, 15) (247, 15) (62, 15)

5. membuat data latih menggunakan algoritma SVM

In [34]:
classifier=svm.SVC(kernel='linear')

In [35]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

6. membuat model evaluasi untuk mengukur tingkat akurasi

In [36]:
X_train_prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction, Y_train)

In [37]:
print('Akurasi data training adalah=', training_data_accuracy)

Akurasi data training adalah= 0.9392712550607287

In [38]:
X_test_prediction=classifier.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction, Y_test)

In [39]:
print('Akurasi data testing adalah=', test_data_accuracy)

Akurasi data testing adalah= 0.9354838709677419

7. membuat model prediksi

In [45]:
input_data=(0, 59, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2)

input_data_as_numpy_array=np.array(input_data)

input_data_reshape=input_data_as_numpy_array.reshape(1,-1)

std_data=scaler.transform(input_data_reshape)
print(std_data)

prediction=classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
    print('Pasien tidak terkena Lung Cancer')
else :
    print('Pasien terkena lung cancer')

[[-1.04978132 -0.44810745 -1.13529242 -1.15035137 -0.99676897  0.99676897
  -1.00975633  0.6968335  -1.12047956  0.892475   -1.12047956  0.85220712
   0.74873631 -0.94029056  0.892475  ]]
[1]
Pasien terkena lung cancer

c:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

8. Simpan model

In [47]:
import pickle

In [49]:
filename='survey_lung_cancer.sav'
pickle.dump(classifier, open(filename, 'wb'))